foreground = "ebdbb2"
border_color = "282b2d"
selected_elements_colors = { background = "444444", foreground = "d4d4d4" }
canvas_colors = { background = "282828", alt_background = "1b252d", foreground = "ebdbb2" }
primary_ui_color = { background = "32302f", foreground = "ebdbb2" }
secondary_ui_color = { background = "1d2021", foreground = "ebdbb2" }
accent_info = { background = "98971a", foreground = "ebdbb2" }
accent_warn = { background = "d79921", foreground = "ebdbb2" }
accent_error = { background = "cc241f", foreground = "ebdbb2" }
clock_highlight_line = { color = "3c3836", width = 2 }
clock_highlight_cycle = "3c3836"
clock_rising_marker = true
variable_default = "648fff"
variable_undef = "dc267f"
variable_highimp = "ffb000"
variable_dontcare = "785ef0"
variable_weak = "bbbbbb"
cursor = { color="ffffff", width=2 }
gesture = { color="ffffff", width=2 }
linewidth = 3
alt_frequency = 0

[colors]
Blue = "648fff"
Purple = "785ef0"
Pink = "dc267f"
Orange = "fe6100"
Yellow = "ffb000"
Green = "ff0000"
